// ------------------------------------------
//  Author: Prof. Taeweon Suh
//          Computer Science & Engineering
//          College of Informatics, Korea Univ.
//  Date:   April 27, 2020
// ------------------------------------------

#include "csd_zynq_peripherals.h"

#define csd_LED_ADDR	0x41200000
#define TIMER_INITIAL	0x400000

.global main
main:
 
	// --------------------------------------
	//  To distribute the learning burden. 
	// -- stack is NOT used in private timer code
	// -- stack will be used in the interrupt code
	// --------------------------------------

	//mrs	r0, cpsr			/* get the current PSR */
	//mvn	r1, #0x1f		/* To mask out the MODE bits (M[4:0]) in CPSR */
	//and	r2, r1, r0
	//orr	r2, r2, #0x1F	/* SYS mode */
	//msr	cpsr, r2

 	// Private Timer Load Register
	ldr r0, =PRIVATE_LOAD
 	ldr r1, =TIMER_INITIAL
 	str r1, [r0]

 	// Private Timer Control Register
  	ldr r0, =PRIVATE_CONTROL
 	mov r1, #1 << 8   // Prescalar
 	orr r1, r1, #7     // IRQ Enable, Auto-Reload, Timer Enable
 	str r1, [r0]

 	// Check out the counter value to make sure the counter is decrementing
  	//ldr r0, =PRIVATE_COUNTER
  	//ldr r1, [r0]
  	//ldr r2, [r0]
  	//ldr r3, [r0]
  	//ldr r4, [r0]
  	//ldr r5, [r0]
  	//ldr r6, [r0]
  	//ldr r7, [r0]
  	//ldr r8, [r0]

  	ldr r0, =PRIVATE_COUNTER
  	ldr r1, =PRIVATE_STATUS

	// Turn on LEDs just for testing
 	ldr  r10, =csd_LED_ADDR
	mov  r11, #0xF
	strb r11, [r10]

forever:

  	ldr r5, [r0]   // Read the counter value
  	ldr r6, [r1]   // Read the status register

	// Toggle LEDs if the counter value reaches to 0
	cmp r6, #1
	b csd_main
	eoreq  r11, r11, #0xFF
	streqb r11, [r10]
	moveq  r12, #1
	streq  r12, [r1] // to clear sticky bit in the status register

  	b forever
